version: "3.8"
services:
  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mssql
    environment:
      spring.datasource.url: jdbc:sqlserver://mssqlserver:1433;databaseName=demo;encrypt=true;trustServerCertificate=true;
  mssql:
    container_name: mssqlserver
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Rubikcube200@