version: "3.8"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Rubikcube200@"
      ACCEPT_EULA: "Y"